#!/bin/ash

set -e  # exit on error
set -u  # no unset variables
set -x  # show rsync command

rsync \
  --recursive \
  --times \
  --omit-dir-times \
  --prune-empty-dirs \
  --size-only \
  --sparse \
  ${RSYNC_OPTIONS} \
  --include-from="/tmp/include.list" \
  --exclude="*" \
  --human-readable \
  --stats \
  -e "ssh ${SSH_OPTIONS} -p ${PORT}" \
  "${SOURCE}" "${LOGIN}@${HOST}:${TARGET}"
