#!/usr/bin/env bash

set -e        # exit on error
set -u        # no unset variables
set -o xtrace # show rsync command

rsync --verbose \
  --recursive \
  --times \
  --omit-dir-times \
  --prune-empty-dirs \
  --copy-links \
  --size-only \
  --sparse \
  ${RSYNC_OPTIONS} \
  --include-from="/tmp/media-sync.list" \
  --exclude="*" \
  --human-readable \
  --info="progress2" \
  --stats \
  -e "ssh -o StrictHostKeyChecking=no -p ${PORT}" \
  "${SOURCE}" "${LOGIN}@${HOST}:${TARGET}"
